"""migration

Revision ID: 008
Revises: 007
Create Date: 2025-04-15 12:29:51.180504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mobile_number',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mobile_number',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
